// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: proto/channel.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All channel types are the Discord channel types +1
type ChannelType int32

const (
	ChannelType_CHANNEL_TYPE_UNSPECIFIED          ChannelType = 0
	ChannelType_CHANNEL_TYPE_GUILD_TEXT           ChannelType = 1
	ChannelType_CHANNEL_TYPE_DM                   ChannelType = 2
	ChannelType_CHANNEL_TYPE_GUILD_VOICE          ChannelType = 3
	ChannelType_CHANNEL_TYPE_GROUP_DM             ChannelType = 4
	ChannelType_CHANNEL_TYPE_GUILD_CATEGORY       ChannelType = 5
	ChannelType_CHANNEL_TYPE_GUILD_NEWS           ChannelType = 6
	ChannelType_CHANNEL_TYPE_UNUSED_7             ChannelType = 7
	ChannelType_CHANNEL_TYPE_UNUSED_8             ChannelType = 8
	ChannelType_CHANNEL_TYPE_UNUSED_9             ChannelType = 9
	ChannelType_CHANNEL_TYPE_GUILD_NEWS_THREAD    ChannelType = 10
	ChannelType_CHANNEL_TYPE_GUILD_PUBLIC_THREAD  ChannelType = 11
	ChannelType_CHANNEL_TYPE_GUILD_PRIVATE_THREAD ChannelType = 12
	ChannelType_CHANNEL_TYPE_GUILD_STAGE_VOICE    ChannelType = 13
	ChannelType_CHANNEL_TYPE_GUILD_DIRECTORY      ChannelType = 14
	ChannelType_CHANNEL_TYPE_GUILD_FORUM          ChannelType = 15
	ChannelType_CHANNEL_TYPE_GUILD_MEDIA          ChannelType = 16
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0:  "CHANNEL_TYPE_UNSPECIFIED",
		1:  "CHANNEL_TYPE_GUILD_TEXT",
		2:  "CHANNEL_TYPE_DM",
		3:  "CHANNEL_TYPE_GUILD_VOICE",
		4:  "CHANNEL_TYPE_GROUP_DM",
		5:  "CHANNEL_TYPE_GUILD_CATEGORY",
		6:  "CHANNEL_TYPE_GUILD_NEWS",
		7:  "CHANNEL_TYPE_UNUSED_7",
		8:  "CHANNEL_TYPE_UNUSED_8",
		9:  "CHANNEL_TYPE_UNUSED_9",
		10: "CHANNEL_TYPE_GUILD_NEWS_THREAD",
		11: "CHANNEL_TYPE_GUILD_PUBLIC_THREAD",
		12: "CHANNEL_TYPE_GUILD_PRIVATE_THREAD",
		13: "CHANNEL_TYPE_GUILD_STAGE_VOICE",
		14: "CHANNEL_TYPE_GUILD_DIRECTORY",
		15: "CHANNEL_TYPE_GUILD_FORUM",
		16: "CHANNEL_TYPE_GUILD_MEDIA",
	}
	ChannelType_value = map[string]int32{
		"CHANNEL_TYPE_UNSPECIFIED":          0,
		"CHANNEL_TYPE_GUILD_TEXT":           1,
		"CHANNEL_TYPE_DM":                   2,
		"CHANNEL_TYPE_GUILD_VOICE":          3,
		"CHANNEL_TYPE_GROUP_DM":             4,
		"CHANNEL_TYPE_GUILD_CATEGORY":       5,
		"CHANNEL_TYPE_GUILD_NEWS":           6,
		"CHANNEL_TYPE_UNUSED_7":             7,
		"CHANNEL_TYPE_UNUSED_8":             8,
		"CHANNEL_TYPE_UNUSED_9":             9,
		"CHANNEL_TYPE_GUILD_NEWS_THREAD":    10,
		"CHANNEL_TYPE_GUILD_PUBLIC_THREAD":  11,
		"CHANNEL_TYPE_GUILD_PRIVATE_THREAD": 12,
		"CHANNEL_TYPE_GUILD_STAGE_VOICE":    13,
		"CHANNEL_TYPE_GUILD_DIRECTORY":      14,
		"CHANNEL_TYPE_GUILD_FORUM":          15,
		"CHANNEL_TYPE_GUILD_MEDIA":          16,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_channel_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_proto_channel_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_proto_channel_proto_rawDescGZIP(), []int{0}
}

type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ChannelType            `protobuf:"varint,2,opt,name=type,proto3,enum=proto.ChannelType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_proto_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_proto_channel_proto_rawDescGZIP(), []int{0}
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetType() ChannelType {
	if x != nil {
		return x.Type
	}
	return ChannelType_CHANNEL_TYPE_UNSPECIFIED
}

var File_proto_channel_proto protoreflect.FileDescriptor

const file_proto_channel_proto_rawDesc = "" +
	"\n" +
	"\x13proto/channel.proto\x12\x05proto\"E\n" +
	"\aChannel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.proto.ChannelTypeR\x04type*\x98\x04\n" +
	"\vChannelType\x12\x1c\n" +
	"\x18CHANNEL_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CHANNEL_TYPE_GUILD_TEXT\x10\x01\x12\x13\n" +
	"\x0fCHANNEL_TYPE_DM\x10\x02\x12\x1c\n" +
	"\x18CHANNEL_TYPE_GUILD_VOICE\x10\x03\x12\x19\n" +
	"\x15CHANNEL_TYPE_GROUP_DM\x10\x04\x12\x1f\n" +
	"\x1bCHANNEL_TYPE_GUILD_CATEGORY\x10\x05\x12\x1b\n" +
	"\x17CHANNEL_TYPE_GUILD_NEWS\x10\x06\x12\x19\n" +
	"\x15CHANNEL_TYPE_UNUSED_7\x10\a\x12\x19\n" +
	"\x15CHANNEL_TYPE_UNUSED_8\x10\b\x12\x19\n" +
	"\x15CHANNEL_TYPE_UNUSED_9\x10\t\x12\"\n" +
	"\x1eCHANNEL_TYPE_GUILD_NEWS_THREAD\x10\n" +
	"\x12$\n" +
	" CHANNEL_TYPE_GUILD_PUBLIC_THREAD\x10\v\x12%\n" +
	"!CHANNEL_TYPE_GUILD_PRIVATE_THREAD\x10\f\x12\"\n" +
	"\x1eCHANNEL_TYPE_GUILD_STAGE_VOICE\x10\r\x12 \n" +
	"\x1cCHANNEL_TYPE_GUILD_DIRECTORY\x10\x0e\x12\x1c\n" +
	"\x18CHANNEL_TYPE_GUILD_FORUM\x10\x0f\x12\x1c\n" +
	"\x18CHANNEL_TYPE_GUILD_MEDIA\x10\x10B+Z)github.com/kkrypt0nn/aegisbot/proto;protob\x06proto3"

var (
	file_proto_channel_proto_rawDescOnce sync.Once
	file_proto_channel_proto_rawDescData []byte
)

func file_proto_channel_proto_rawDescGZIP() []byte {
	file_proto_channel_proto_rawDescOnce.Do(func() {
		file_proto_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_channel_proto_rawDesc), len(file_proto_channel_proto_rawDesc)))
	})
	return file_proto_channel_proto_rawDescData
}

var file_proto_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_channel_proto_goTypes = []any{
	(ChannelType)(0), // 0: proto.ChannelType
	(*Channel)(nil),  // 1: proto.Channel
}
var file_proto_channel_proto_depIdxs = []int32{
	0, // 0: proto.Channel.type:type_name -> proto.ChannelType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_channel_proto_init() }
func file_proto_channel_proto_init() {
	if File_proto_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_channel_proto_rawDesc), len(file_proto_channel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_channel_proto_goTypes,
		DependencyIndexes: file_proto_channel_proto_depIdxs,
		EnumInfos:         file_proto_channel_proto_enumTypes,
		MessageInfos:      file_proto_channel_proto_msgTypes,
	}.Build()
	File_proto_channel_proto = out.File
	file_proto_channel_proto_goTypes = nil
	file_proto_channel_proto_depIdxs = nil
}
