// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.4
// source: proto/member.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Bot           bool                   `protobuf:"varint,2,opt,name=bot,proto3" json:"bot,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_member_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Member) GetBot() bool {
	if x != nil {
		return x.Bot
	}
	return false
}

func (x *Member) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_member_proto protoreflect.FileDescriptor

const file_proto_member_proto_rawDesc = "" +
	"\n" +
	"\x12proto/member.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n" +
	"\x06Member\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03bot\x18\x02 \x01(\bR\x03bot\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB+Z)github.com/kkrypt0nn/aegisbot/proto;protob\x06proto3"

var (
	file_proto_member_proto_rawDescOnce sync.Once
	file_proto_member_proto_rawDescData []byte
)

func file_proto_member_proto_rawDescGZIP() []byte {
	file_proto_member_proto_rawDescOnce.Do(func() {
		file_proto_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_member_proto_rawDesc), len(file_proto_member_proto_rawDesc)))
	})
	return file_proto_member_proto_rawDescData
}

var file_proto_member_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_member_proto_goTypes = []any{
	(*Member)(nil),                // 0: proto.Member
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_proto_member_proto_depIdxs = []int32{
	1, // 0: proto.Member.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_member_proto_init() }
func file_proto_member_proto_init() {
	if File_proto_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_member_proto_rawDesc), len(file_proto_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_member_proto_goTypes,
		DependencyIndexes: file_proto_member_proto_depIdxs,
		MessageInfos:      file_proto_member_proto_msgTypes,
	}.Build()
	File_proto_member_proto = out.File
	file_proto_member_proto_goTypes = nil
	file_proto_member_proto_depIdxs = nil
}
