name: Aegisbot CD (Deploy Website)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_website:
    uses: kkrypt0nn/actions/.github/workflows/deploy_website.yaml@4370b5407f227731cd795ae57ba6336ef6dc777c # v0.1.0
    with:
      working-directory: website
      node-version: "24.16.0"
      build-path: build
