name: Label Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/labels.yaml"

permissions:
  contents: read
  issues: write

jobs:
  label_sync:
    uses: kkrypt0nn/actions/.github/workflows/label_sync.yaml@f87e74587c75a99d661e5966fc41552d106a3712 # v0.1.1
