name: Labeler

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    uses: kkrypt0nn/actions/.github/workflows/labeler.yaml@f87e74587c75a99d661e5966fc41552d106a3712 # v0.1.1
